name: Test
on:
  push

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "19"

      - name: Install Dependencies
        run: npm install

      - name: Type Check
        run: npm run typecheck
